version: '3.8'

services:
  redis:
    container_name: "Redis"
    restart: always
    image: "redis:7.2.3"
    ports:
      - "6379:6379"

  mssql:
    container_name: "mssql2022"
    restart: always
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "P@ssword!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

