<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Fido2.Models" Version="3.0.1" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.2.1" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MyBlog.Common\MyBlog.Common.csproj" />
		<ProjectReference Include="..\MyBlog.Domain\MyBlog.Domain.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<NoWarn>CS8981</NoWarn>
	</PropertyGroup>
</Project>