<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Fido2.Models" />
		<PackageReference Include="Microsoft.Data.SqlClient" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.IdentityModel.Tokens" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="System.Data.SqlClient" />
		<PackageReference Include="System.Linq.Dynamic.Core" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MyBlog.Common\MyBlog.Common.csproj" />
		<ProjectReference Include="..\MyBlog.Domain\MyBlog.Domain.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<NoWarn>CS8981</NoWarn>
	</PropertyGroup>
</Project>