<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" />
		<PackageReference Include="Azure.Storage.Common" />
		<PackageReference Include="Microsoft.AspNetCore.Http" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\MyBlog.Domain\MyBlog.Domain.csproj" />
	</ItemGroup>
</Project>