<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="Azure.Storage.Common" Version="12.22.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\MyBlog.Domain\MyBlog.Domain.csproj" />
	</ItemGroup>
</Project>