<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
		<PackageReference Include="Fido2" Version="3.0.1" />
		<PackageReference Include="LanguageDetection.NETStandard" Version="1.3.1" />
		<PackageReference Include="MassTransit.Abstractions" Version="8.2.5" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.2.1" />
		<PackageReference Include="Profanity.Detector" Version="0.1.8" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MyBlog.Common\MyBlog.Common.csproj" />
		<ProjectReference Include="..\MyBlog.Data\MyBlog.Data.csproj" />
		<ProjectReference Include="..\MyBlog.Domain\MyBlog.Domain.csproj" />
	</ItemGroup>
</Project>