<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs"  />
		<PackageReference Include="Fido2"  />
		<PackageReference Include="LanguageDetection.NETStandard"  />
		<PackageReference Include="MassTransit.Abstractions"  />
		<PackageReference Include="Microsoft.AspNetCore.Http"  />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"  />
		<PackageReference Include="Microsoft.Data.SqlClient"  />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.IdentityModel.Tokens"  />
		<PackageReference Include="Profanity.Detector"  />
		<PackageReference Include="SixLabors.ImageSharp"  />
		<PackageReference Include="Swashbuckle.AspNetCore"  />
		<PackageReference Include="System.Data.SqlClient"  />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt"  />
		<PackageReference Include="System.Linq.Dynamic.Core"  />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MyBlog.Common\MyBlog.Common.csproj" />
		<ProjectReference Include="..\MyBlog.Data\MyBlog.Data.csproj" />
		<ProjectReference Include="..\MyBlog.Domain\MyBlog.Domain.csproj" />
	</ItemGroup>
</Project>