name: Frontend build + test

on:
  pull_request:
    branches: [ "slave" ]
    paths:
      - 'React/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.11.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: React/my-blog/package-lock.json

    - name: Install dependencies
      run: npm --prefix React/my-blog install

    - name: Run tests
      run: npm --prefix React/my-blog test -- --coverage
    
    - name: Build
      env:
          CI: false
      run: npm --prefix React/my-blog run build
