name: Frontend build + test

on:
  push:
    branches: [ "slave" ]
  pull_request:
    branches: [ "slave" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.0]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: React/my-blog/package-lock.json
    - run: npm --prefix React/my-blog install
    - run: npm --prefix React/my-blog run build
      timeout-minutes: 5
    - run: npm --prefix React/my-blog test -- --coverage
