name: Backend Build + Test

on:
  pull_request:
    branches:
      - slave
    paths:
      - '**/*.cs'
      - '**/*.props'
      - '**/*.csproj'
      - '**/*.sln'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Unit Tests
      run: dotnet test MyBlog.UnitTests/MyBlog.UnitTests.csproj

    - name: Run Functional Tests
      run: dotnet test MyBlog.FunctionalTests/MyBlog.FunctionalTests.csproj
